# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Use R
language: r
sudo: true
cache: packages
warnings_are_errors: false

apt_packages:
  - unrar-free
  - libudunits2-dev
  - libgdal-dev
  - libgeos-dev
  - libproj-dev

# for codecov
r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
  - travis_wait 120 Rscript -e 'pkgdown::build_site()'

os:
  - linux
Comment:
  - osx
